### ISSUE TITLE
DAO Gallerys

### ISSUE THREAD

**Issue by madjin** [NEON-BUIDL/DAOtown#10]
These would be the experiences the buildings would lead to

- Tribute:
  - Noise
  - Red
  - Flamingo
  - Neon
  - Glimmer
- M3:
  - M3 Mart
  - MetaFactory
  
Would be useful to have 2D infinite canvas moodboards / references for the galleries for each, perhaps a folder in each in the github

**Comment by Arashi-Chan** [comment]
Posting some screenshots showing progress of my work on the Glimmer gallery world:

![image](https://github.com/NEON-BUIDL/DAOtown/assets/109450887/416ba87e-43d1-4e0c-b586-5692f44c6205)
![image](https://github.com/NEON-BUIDL/DAOtown/assets/109450887/f4b0bd86-32c8-4b6e-b417-d969e8e8df26)
![image](https://github.com/NEON-BUIDL/DAOtown/assets/109450887/a1fe5019-6d2c-4f86-9cec-e212c302e6da)
![image](https://github.com/NEON-BUIDL/DAOtown/assets/109450887/e693934c-c23c-4321-a391-37d03c76f2df)
![image](https://github.com/NEON-BUIDL/DAOtown/assets/109450887/08417cf6-fdf6-464a-8ebc-5010b9f3029f)
![image](https://github.com/NEON-BUIDL/DAOtown/assets/109450887/8829a4d2-f1f1-476b-9d3b-c3aedeca5436)

After meeting with Ed from Glimmer and Jack, I have a few things on my list of updates:

- Model the current bamboo NFT display into two or three different versions, each one a different aspect ratio 
- enable functionality of non-static images for some of Glimmer's NFT's that are not static images
- decorate the exterior of each Dojo-like building in theme with a Japanese / Zen Garden

Some questions for moving forward:
- if Glimmer possessed the Hyperfy world with this gallery and made me a collaborator on it, would that make it so I can change up the Bamboo displays according to their desired layout / curation plan for the gallery, then they could plug what is in their wallet directly into those displays? 
- So in essence, I would be placing blank NFT bamboo displays around the world, and they could fill that in later directly from their wallet?

**Comment by decentralize-dfw** [comment]
DFW LOG 1/ 29062023
with Noise DAO, we had two productive meetings for around an hour. I made a research their taste and their collections and assembled a couple of jpegs like a mood board to make it clear to everyone. 
![WalletReferances-Low copy](https://github.com/NEON-BUIDL/DAOtown/assets/115695363/635accce-66c3-4bae-8df3-64f051a5d355)

First keywords: (later they used to generate ai visuals)
black and white, pixel / glitch, metamorphosis. sound SENSITIVE, primitive / aggressive, sharp geometries, dark, underground. zen-like villain or reverse, minimalist
![Merged1-low copy](https://github.com/NEON-BUIDL/DAOtown/assets/115695363/28155f73-9f91-4bd9-937a-99ec3e2d4baf)


 and my first idea of approach was to solve a multicomplex use frame in a single volume like Berghain, but that might limit the fun of exposing collections with different curation approaches and we decided to scatter the functions around in a world with different edifices to create a better experience. 

Then, a new draft sketch of urban planning of the world has been designed, to answer the needs of different collections, briefly.  The main idea was to create an organic middle space defined by related uses. 
![1stdraft-LOW](https://github.com/NEON-BUIDL/DAOtown/assets/115695363/8c5ead32-2638-4555-92e8-97d6e7bcee63)

The outcome for this urban design is constructed in a Hyperfy world to test the spaces and their distances, as well as different skybox/hdr options. 
For a temporary nightclub, Holy Shadow HQ is tested with 3 bloom layers as an experiment, and we decided to keep it there. 
Early test stage of the bloom layers with 0XDEAFBEEF's work: [https://twitter.com/D__F__W__/status/1674380484678123521?s=20](url)

https://github.com/NEON-BUIDL/DAOtown/assets/115695363/237598e5-d9d8-449d-b447-d531812023e4
 
Further, once DAO members decided that they will need 5 different spaces to exhibit their collections + 1 for meetings and 1 for music areas like clubbing or performance.  

1- High-Frequency Building
It is a set of 16 listening hubs in a single structure, dedicated to High-Frequency Ep, published by Noise DAO. But later, with volume 2 and more, we might add one or two more floors on top depending on the published materials.  The main idea of the design is to have floating techno bungalows connected to a weird structure that flows horizontally. While the hubs are fully black, they have frosted glass floors that might reflect the color of the inside (special lights for each cover) without disturbing the experience.  [making of - [https://twitter.com/decentralize___/status/1674377979722334209?s=20](url) ] For now, we locked the design. 

![image222](https://github.com/NEON-BUIDL/DAOtown/assets/115695363/3fbbd0d8-e9ad-4222-85c6-3061a9c2d3fc)

2-experimental space for Creative Audio Museum
it has 16 horizontal corridor-like cubes, with a single yet experimental axis of the promenade. Since the exhibition material is quite experimental, I bet on a very experimental design at first, but the problem was that the building itself is too experimental which complicates the observation experience, with narrow corridors that create a virtual claustrophobia. It was a good test, but we decided that we need more neat space with less spatial experimental elements that would enough space for the artwork itself.  [ [https://twitter.com/decentralize___/status/1669633743961595904?s=20](url) ]

3-Music Collection
designed a new tower for the music collection, and each small cubes are like a listening hub - a mix of ny guggenheim + nagakin capsule tower - and we can increase or decrease the number of modules depending on the number of assets. It has to the axis of vertical ramps with an order of visit for artworks. Since they are quite close as a space (for each) and spatial audio could mess up the experience with that amount of elements, the only solution is to host the audio artworks via Webviewer that isolates the music on each user's browser. As a design, the feedback from members is that they liked the building so we keep it. 
![image](https://github.com/NEON-BUIDL/DAOtown/assets/115695363/a71a14ba-c4e5-4d0b-8a71-65dfb2e5c732)
![image22](https://github.com/NEON-BUIDL/DAOtown/assets/115695363/454f524e-096b-4cb0-8bc7-2f82f826ac3a)
![metaboilerism1](https://github.com/NEON-BUIDL/DAOtown/assets/115695363/7c815a45-b999-4b55-83e9-65250bb08184)
![metaboilerism3](https://github.com/NEON-BUIDL/DAOtown/assets/115695363/b1864bc0-b104-4f3a-9b0f-6a7c31ffacd5)

4- Meeting/Performance Building
We decided to have this building also, with its virtual post-industrial vibe with some skatepark flavor in it, the function of it is not well defined yet, it has to be organized better as an interior scheme. With its 4 layers of bloom, the space and the facade work very impressively.
https://github.com/NEON-BUIDL/DAOtown/assets/115695363/1d422200-1cab-4410-8cc5-2373daca2b5f
For some virtual performances of artists, a new virtual drum machine to expand what could be a performance, besides streaming or using the play, and maybe that machine needs to be developed further. but it has a huge amount of potential for immersive beat cooking. 
![dRUMmACHINEcONTROLS](https://github.com/NEON-BUIDL/DAOtown/assets/115695363/91936c13-fa2a-4c0d-8ad8-a83b545574d6)


NEXT

1-Finalize existing buildings, and add artworks on them
2-Locate them wisely in the world that would organically define an immersive public space
3-Create an in-between zone before entering the world to explain aims for a complete stranger of Noise Dao, Neon Buidl or Hyperfy.
4-MuWave Building
5-Experimental Audio Building
6-4 versions of avatars
